# @package __global__

datasource:
  max_sample_rate: 44100
  max_channels: 2

  train: egs/slakh-discovery/train
  valid: egs/slakh-discovery/test
  evaluate: egs/slakh-discovery/test
  generate: egs/slakh-discovery/test
